<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KGRR886" ignored="4" name="Default test" tests="4" failures="2" timestamp="11 Sep 2022 05:58:46 GMT" time="77.657" errors="0">
  <testcase name="Test1" time="0.007" classname="testcases.HomeTest"/>
  <testcase name="Test1" time="17.3" classname="testcases.SimplilearnLoginTest"/>
  <testcase name="Test2" time="0.0" classname="testcases.SimplilearnLoginTest">
    <failure type="org.testng.TestNGException" message="
Parameter &amp;apos;email&amp;apos; is required by @Test on method Test2 but has not been marked @Optional or defined
in C:\Users\Dell\AppData\Local\Temp\testng-eclipse-758293397\testng-customsuite.xml">
      <![CDATA[org.testng.TestNGException: 
Parameter 'email' is required by @Test on method Test2 but has not been marked @Optional or defined
in C:\Users\Dell\AppData\Local\Temp\testng-eclipse-758293397\testng-customsuite.xml
	at org.testng.internal.Parameters.createParams(Parameters.java:248)
	at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:286)
	at org.testng.internal.Parameters.createParameters(Parameters.java:547)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:672)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1316)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1044)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1134)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.001" classname="testcases.SimplilearnLoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at testcases.SimplilearnLoginTest.Test3(SimplilearnLoginTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase name="@BeforeTest datasetup" time="0.0" classname="testcases.Baseclass">
    <ignored/>
  </testcase> <!-- @BeforeTest datasetup -->
  <testcase name="@BeforeTest datasetup" time="0.0" classname="testcases.Baseclass">
    <ignored/>
  </testcase> <!-- @BeforeTest datasetup -->
  <testcase name="@AfterTest datacleanup" time="0.0" classname="testcases.Baseclass">
    <ignored/>
  </testcase> <!-- @AfterTest datacleanup -->
  <testcase name="@AfterTest datacleanup" time="0.0" classname="testcases.Baseclass">
    <ignored/>
  </testcase> <!-- @AfterTest datacleanup -->
</testsuite> <!-- Default test -->
